FROM ronin:ubuntu

LABEL maintainer="postmodern.mod3@gmail.com"

# Install common utils and create the user
RUN apt-get update -qq && \
    apt-get install -qq -y sudo tar zip vim netstat-nat net-tools iputils-ping traceroute host whois netcat wget curl git && \
    apt-get clean && \
    useradd -m -s /bin/bash ronin && \
    echo "ronin ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/ronin && \
    chmod 0440 /etc/sudoers.d/ronin && \
    usermod -aG sudo ronin && \
    touch /home/ronin/.sudo_as_admin_successful && \
    chown ronin:ronin /home/ronin/.sudo_as_admin_successful

USER ronin
WORKDIR /home/ronin

CMD ["/bin/bash"]
